mongo-db:
  #build: ./db-server
  image: mongo
  ports:
    - 27017:27017
  hostname: mongodbhost

app-ms:
  #build: .
  image: rmelos/backarquitectura_app-ms
  ports:
    - "5000:5000"
  links:
    - mongo-db
